/**
 * Created by dinanjanag on 8/5/19.
 */

const LOAD_REVIEWS = 'LOAD_REVIEWS';
const LOAD_REVIEWS_FULFILLED = 'LOAD_REVIEWS_FULFILLED';
const SELECT_REVIEW = 'SELECT_REVIEW';
const ENTER_REVIEW = 'ENTER_REVIEW';
const ENTER_RATING = 'ENTER_RATING';
const SAVE_REVIEW = 'SAVE_REVIEW';
const SAVE_REVIEW_FULFILLED = 'SAVE_REVIEW_FULFILLED';
const DELETE_REVIEW = 'DELETE_REVIEW';
const DELETE_REVIEW_FULFILLED = 'DELETE_REVIEW_FULFILLED';
const CLEAN_MESSAGES = 'CLEAN_MESSAGES';

export {
  LOAD_REVIEWS,
  LOAD_REVIEWS_FULFILLED,
  SELECT_REVIEW,
  SAVE_REVIEW,
  SAVE_REVIEW_FULFILLED,
  DELETE_REVIEW,
  DELETE_REVIEW_FULFILLED,
  ENTER_REVIEW,
  ENTER_RATING,
  CLEAN_MESSAGES,
};