/**
 * Created by dinanjanag on 8/5/19.
 */

const LOAD_REVIEWS = 'LOAD_REVIEWS';
const LOAD_REVIEWS_FULFILLED = 'LOAD_REVIEWS_FULFILLED';
const SELECT_REVIEW = 'SELECT_REVIEW';
const SAVE_REVIEW = 'SAVE_REVIEW';
const DELETE_REVIEW = 'DELETE_REVIEW';

export {
  LOAD_REVIEWS,
  LOAD_REVIEWS_FULFILLED,
  SELECT_REVIEW,
  SAVE_REVIEW,
  DELETE_REVIEW,
};